# Generated by Django 3.0.3 on 2020-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_piechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='piechart',
            name='nameA',
            field=models.CharField(default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='piechart',
            name='nameB',
            field=models.CharField(default='B', max_length=50),
        ),
        migrations.AddField(
            model_name='piechart',
            name='nameC',
            field=models.CharField(default='C', max_length=50),
        ),
    ]
