# Generated by Django 3.0.3 on 2020-06-23 05:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200623_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barchart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
