# Generated by Django 3.0.8 on 2020-08-02 05:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200623_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchart',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=8), size=None),
        ),
    ]
