# Generated by Django 3.0.3 on 2020-06-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200623_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barchart',
        ),
        migrations.DeleteModel(
            name='Piechart',
        ),
    ]
