# Generated by Django 3.0.8 on 2020-08-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200802_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piechart',
            name='a',
        ),
        migrations.RemoveField(
            model_name='piechart',
            name='b',
        ),
        migrations.RemoveField(
            model_name='piechart',
            name='c',
        ),
        migrations.RemoveField(
            model_name='piechart',
            name='nameA',
        ),
        migrations.RemoveField(
            model_name='piechart',
            name='nameB',
        ),
        migrations.RemoveField(
            model_name='piechart',
            name='nameC',
        ),
        migrations.AddField(
            model_name='piechart',
            name='data',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piechart',
            name='lable',
            field=models.CharField(default='', max_length=50),
        ),
    ]
