# Generated by Django 3.0.8 on 2020-08-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200802_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piechart',
            old_name='lable',
            new_name='label',
        ),
    ]
