# Generated by Django 3.0.8 on 2020-08-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200802_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchart',
            name='data',
            field=models.IntegerField(default=0),
        ),
    ]
